---
- name: Check the latest stable version of Go
  uri:
    url: "{{ go.api_url }}"
    return_content: true
  register: go_rmt_ver

- name: Check if the latest version of Go installed already
  command: "go version"
  register: go_local_ver
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Install Go
  block:
    - name: Install Go
      unarchive:
        src: "{{ go.base_url }}/{{ go_rmt_ver.content }}{{ go.file_suffix }}"
        dest: "{{ go.install }}"
        remote_src: true

    - name: Create a symbolic links for Go binaries
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      with_items: "{{ go.symlinks }}"

  when: go_rmt_ver.content not in go_local_ver.stdout | default('notinstalled')
