---
- name: Install Go
  block:
    - name: Get the latest stable version of Go
      uri:
        url: https://golang.org/VERSION?m=text
        return_content: true
      register: go_version

    - name: Download Go
      get_url:
        url: '{{ go.src }}'
        dest: '{{ go.dest }}'

    - name: Install Go
      unarchive:
        src: '{{ go.dest }}'
        dest: '{{ go.install }}'
        copy: false

    - name: Create a symbolic links for Go binaries
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        force: true
      with_items: '{{ go.symlinks }}'
