---

- name: Get Shellcheck releases
  uri:
    url: "{{ shellcheck.api_url }}"
    return_content: true
  register: shellcheck_releases

- name: Find the latest version of Shellcheck
  set_fact:
    shellcheck_remote_version: "{{ ( shellcheck_releases.content |\
      from_json).tag_name }}"

- name: Check if the latest version of Shellcheck installed already
  command: "{{ shellcheck.install }}/shellcheck version"
  register: shellcheck_local_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install Shellcheck
  unarchive:
    src: "{{ shellcheck.base_url }}/{{ shellcheck.download_file }}"
    dest: "{{ shellcheck.install }}"
    remote_src: true
    extra_opts: [--strip-components=1]
  when: >-
    shellcheck_remote_version not in shellcheck_local_version.stdout |
    default('notinstalled')
