---
sudo: required
language: python
services:
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - cd ../
  - mv winit-ansible winit
  - cd winit
script:
  - molecule test --all
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
