---
- name: Upgrade pip and enable pip bash completion
  block:
    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3
        extra_args: --upgrade

    - name: Enable pip bash completion
      shell: 'pip completion --bash > {{ python.pip.bash_completion_dest }}'
      changed_when: false
  when:
    - python3_enabled | bool
