---
- name: (Debian/Ubuntu) Install cloudsdk
  block:
    - name: (Debian/Ubuntu) Add cloudsdk apt key
      apt_key:
        url: "{{ cloudsdk.deb_config.repo_key }}"
        keyring: "{{ cloudsdk.deb_config.keyring }}"

    - name: (Debian/Ubuntu) Add cloudsdk apt repository
      apt_repository:
        repo: "{{ cloudsdk.deb_config.repo_url }}"

    - name: (Debian/Ubuntu) Install google-cloud-sdk and kubectl
      apt:
        name: "{{ cloudsdk.deb_config.install_list }}"
        update_cache: true
        state: present
