---
- name: Install APT keys and repository
  block:
    - name: "(CentOS/RHEL) Install prerequisites"
      yum:
        name: "{{ cloudsdk.centos.requirements }}"
        state: present

    - name: "(CentOS/RHEL) Add cloud-sdk YUM repository"
      yum_repository:
        name: google-cloud-sdk
        description: Google Cloud SDK
        baseurl: "{{ cloudsdk.centos.repo_url }}"
        enabled: true
        repo_gpgcheck: true
        gpgcheck: true
        gpgkey: "{{ cloudsdk.centos.repo_key }}"

    - name: "(CentOS/RHEL) Install google-cloud-sdk and kubectl"
      yum:
        name: "{{ cloudsdk.centos.install_list }}"
        state: present
  when:
    - cloudsdk_enabled | bool
