---
- name: (CentOS/RHEL) Install cloudsdk
  block:
    - name: (CentOS/RHEL) Add cloudsdk yum repository
      yum_repository:
        name: google-cloud-sdk
        description: Google Cloud SDK
        baseurl: "{{ cloudsdk.rpm_config.repo_url }}"
        enabled: true
        repo_gpgcheck: true
        gpgcheck: true
        gpgkey: "{{ cloudsdk.rpm_config.repo_key }}"

    - name: (CentOS/RHEL) Install google-cloud-sdk and kubectl
      yum:
        name: "{{ cloudsdk.rpm_config.install_list }}"
        state: present
