---

# Import requirements
- import_tasks: requirements/deb.yml
  when:
    - ansible_os_family | lower == "debian"

- import_tasks: requirements/rpm.yml
  when:
    - ansible_os_family | lower == "redhat"

- import_tasks: requirements/common.yml

# awscli
- import_tasks: awscli/common.yml
  when:
    - awscli_enabled | bool

# ansible
- import_tasks: ansible/common.yml
  when:
    - ansible_enabled | bool

# go
- import_tasks: go/common.yml
  when:
    - go_enabled | bool

# cloudsdk
- name: Install cloudsdk
  block:
    - import_tasks: cloudsdk/deb.yml
      when:
        - ansible_os_family | lower == "debian"

    - import_tasks: cloudsdk/rpm.yml
      when:
        - ansible_os_family | lower == "redhat"

    - import_tasks: cloudsdk/common.yml
  when:
    - cloudsdk_enabled | bool

# azurecli
- name: Install azurecli
  block:
    - import_tasks: azurecli/deb.yml
      when:
        - ansible_os_family | lower == "debian"

    - import_tasks: azurecli/rpm.yml
      when:
        - ansible_os_family | lower == "redhat"
  when:
    - azurecli_enabled | bool

# docker
- name: Install Docker
  block:
    - import_tasks: docker/debian.yml
      when:
        - ansible_distribution | lower == "debian"

    - import_tasks: docker/ubuntu.yml
      when:
        - ansible_distribution | lower == "ubuntu"

    - import_tasks: docker/centos.yml
      when:
        - ansible_distribution | lower == "centos"
        - ansible_distribution_major_version == "7"

    - import_tasks: docker/dnf.yml
      when:
        - ansible_distribution | lower == "centos"
        - ansible_distribution_major_version == "8"
  when:
    - docker_enabled | bool
