---
- import_tasks: cloudsdk/debian-ubuntu.yml
  when:
    - ansible_os_family == "Debian"

- import_tasks: cloudsdk/rhel-centos.yml
  when:
    - ansible_os_family == "RedHat"

- import_tasks: cloudsdk/common.yml
