---

# python3 and pip
- import_tasks: python/debian-ubuntu.yml
  when:
    - ansible_os_family | lower == "debian"

- import_tasks: python/centos.yml
  when:
    - ansible_distribution | lower == "centos"

- import_tasks: python/fedora.yml
  when:
    - ansible_distribution | lower == "fedora"

- import_tasks: python/common.yml

# awscli
- import_tasks: awscli/common.yml

# ansible
- import_tasks: ansible/common.yml

# ipython
- import_tasks: ipython/common.yml

# git
- import_tasks: git/common.yml

# go
- import_tasks: go/common.yml

# cloudsdk
- import_tasks: cloudsdk/debian-ubuntu.yml
  when:
    - ansible_os_family | lower == "debian"

- import_tasks: cloudsdk/rhel-centos.yml
  when:
    - ansible_os_family | lower == "redhat"

- import_tasks: cloudsdk/common.yml

# docker
- import_tasks: docker/debian.yml
  when:
    - ansible_distribution | lower == "debian"

- import_tasks: docker/ubuntu.yml
  when:
    - ansible_distribution | lower == "ubuntu"

- import_tasks: docker/centos.yml
  when:
    - ansible_distribution | lower == "centos"

- import_tasks: docker/fedora.yml
  when:
    - ansible_distribution | lower == "fedora"
