---

- name: Get docker-compose releases API
  uri:
    url: "{{ docker_compose.api_url }}"
    return_content: true
  register: docker_compose_releases

- name: Find the latest version of docker-compose
  set_fact:
    docker_compose_remote_version: "{{ ( docker_compose_releases.content |\
      from_json).tag_name }}"

- name: Check if the latest version of docker-compose installed already
  command: "{{ docker_compose.install }}/docker-compose -v"
  register: docker_compose_local_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install docker-compose
  get_url:
    url: "{{ docker_compose.base_url }}/{{ docker_compose_remote_version }}/\
    {{ docker_compose.download_file_name }}"
    dest: "{{ docker_compose.install }}/{{ docker_compose.install_file_name }}"
    force: true
    mode: '0755'
  when: >-
    docker_compose_remote_version not in docker_compose_local_version.stdout |
    default('notinstalled')
