---
# Default docker-compose settings

docker_compose:
  api_url: https://api.github.com/repos/docker/compose/releases/latest
  install: /usr/bin
  base_url: https://github.com/docker/compose/releases/download
  download_file_name: docker-compose-Linux-x86_64
  install_file_name: docker-compose
