---
# Default settings for requirements

requirements:
  pip_config:
    bash_comp_dest: /etc/profile.d/pip_bash_completion.sh
  deb_config:
    install_list:
      - git
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - lsb-release
      - gnupg
      - unzip
      - jq
      - bash-completion
      - python3
      - python3-pip
  rpm_config:
    install_list:
      - git
      - curl
      - gnupg
      - unzip
      - jq
      - which
      - bash-completion
      - python3
