---
# Default settings for requirements

requirements:
  pip:
    bash_comp_dest: /etc/profile.d/pip_bash_completion.sh
  apt:
    - git
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - lsb-release
    - gnupg
    - unzip
    - jq
    - bash-completion
    - python3
    - python3-pip
  yum:
    - git
    - curl
    - gnupg
    - unzip
    - jq
    - which
    - bash-completion
    - python3
    - python3-setuptools
  dnf:
    - git
    - curl
    - gnupg
    - unzip
    - jq
    - which
    - bash-completion
    - python3
