---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-7
    image: centos:7
  - name: fedora-30
    image: fedora:30
  - name: debian-stretch
    image: debian:stretch
  - name: debian-buster
    image: debian:buster
  - name: ubuntu-xenial
    image: ubuntu:xenial
  - name: ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      fedora-30:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: testinfra
  lint:
    name: flake8
