---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-8
    image: centos:8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      centos-8:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: testinfra
  lint:
    name: flake8
