---

- name: Get Helm releases
  uri:
    url: "{{ helm.api_url }}"
    return_content: true
  register: helm_releases

- name: Find the latest version of Helm
  set_fact:
    helm_remote_version: "{{ ( helm_releases.content |\
      from_json).tag_name }}"

- name: Check if the latest version of Helm installed already
  command: "{{ helm.install }}/helm version"
  register: helm_local_version
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Install Helm
  unarchive:
    src: "{{ helm.base_url }}/{{ helm.file_prefix }}{{ helm_remote_version }}\
      {{ helm.file_suffix }}"
    dest: "{{ helm.install }}"
    remote_src: true
    extra_opts: [--strip-components=1]
  when: >-
    helm_remote_version not in helm_local_version.stdout |
    default('notinstalled')

- name: Enable Helm bash completion
  lineinfile:
    create: true
    line: "source <(helm completion bash)"
    dest: '{{ helm.bash_comp_dest }}'
