---
- name: Install npm and yarn
  block:
    - name: Install/Update npm
      npm:
        name: npm
        global: true

    - name: Install yarn
      npm:
        name: yarn
        global: true

    - name: Enable npm bash completion
      lineinfile:
        create: true
        line: "source <(npm completion bash)"
        dest: '{{ nodejs.npm_bash_comp_dest }}'
        mode: 0644
