---
- name: (Debian/Ubuntu) Install NodeJS 12 (LTS)
  block:
    - name: (Debian/Ubuntu) Download NodeJS 12 (LTS) repo installer script
      get_url:
        url: "{{ nodejs.deb_config.repo_script }}"
        dest: "{{ nodejs.deb_config.download_dest }}"
        mode: '0755'
      changed_when: false

    - name: (Debian/Ubuntu) Run NodeJS 12 (LTS) repo installer script
      command: "{{ nodejs.deb_config.download_dest }}"
      changed_when: false

    - name: (Debian/Ubuntu) Install NodeJS 12 (LTS)
      apt:
        name: nodejs
        state: present
        update_cache: true

    - name: (Debian/Ubuntu) Install/Update npm
      npm:
        name: npm
        global: true

    - name: (Debian/Ubuntu) Install yarn
      npm:
        name: yarn
        global: true
