---
- name: (CentOS/RHEL) Install NodeJS 12 (LTS)
  block:
    - name: (CentOS/RHEL) Download NodeJS 12 (LTS) repo installer script
      get_url:
        url: "{{ nodejs.rpm_config.repo_script }}"
        dest: "{{ nodejs.rpm_config.download_dest }}"
        mode: '0755'

    - name: (CentOS/RHEL) Run NodeJS 12 (LTS) installer script
      command: "{{ nodejs.rpm_config.download_dest }}"
      changed_when: false

    - name: (CentOS/RHEL) Install NodeJS 12 (LTS)
      yum:
        name: nodejs
        state: present

    - name: (CentOS/RHEL) Install/Update npm
      npm:
        name: npm
        global: true

    - name: (CentOS/RHEL) Install yarn
      npm:
        name: yarn
        global: true
