---
- name: (CentOS/RHEL) Install requirements
  block:
    - name: (CentOS/RHEL) Install requirements
      yum:
        name: "{{ requirements.yum }}"
        state: present
        update_cache: yes
