---
- name: Install pip and virtualenv, enable pip bash completion
  block:
    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3
        extra_args: --upgrade

    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3
        extra_args: --upgrade

    - name: Enable pip bash completion
      shell: 'pip completion --bash > {{ requirements.pip.bash_comp_dest }}'
      changed_when: false
