---
- name: Install pip and virtualenv, enable pip bash completion
  block:
    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3
        extra_args: --upgrade

    - name: Install virtualenv and virtualenvwrapper and IPython
      pip:
        name:
          - virtualenv
          - virtualenvwrapper
          - ipython
        executable: pip3
        extra_args: --upgrade

    - name: Enable pip bash completion
      lineinfile:
        create: true
        line: "source <(pip completion --bash)"
        dest: '{{ requirements.pip_config.bash_comp_dest }}'
        mode: 0644

    - name: Copy virtualenvwrapper config file
      copy:
        src: venvwrapper.sh
        dest: '{{ requirements.virtualenvwrapper.venvwrapper_config_dest }}'
        mode: 0644
