---
- name: Install APT keys and repository
  block:
    - name: "(Debian/Ubuntu) Install prerequisites"
      apt:
        name: "{{ cloudsdk.debian.requirements }}"
        update_cache: true
        state: present

    - name: "(Debian/Ubuntu) Add cloud-sdk APT Signing Key"
      apt_key:
        url: "{{ cloudsdk.debian.key }}"
        keyring: "{{ cloudsdk.debian.keyring }}"

    - name: "(Debian/Ubuntu) Add cloud-sdk APT repository"
      apt_repository:
        repo: "{{ cloudsdk.debian.url }}"
  when:
    - gcloud == "present"
      or kubectl == "present"

- name: "(Debian/Ubuntu) Install gcloud"
  apt:
    name: google-cloud-sdk
    update_cache: true
    state: "{{ gcloud }}"

- name: "(Debian/Ubuntu) Install kubectl"
  apt:
    name: kubectl
    update_cache: true
    state: "{{ kubectl }}"
