---
- name: (Ubuntu) Install docker-ce
  block:
    - name: "(Ubuntu) Add docker apt key"
      apt_key:
        url: "{{ docker.ubuntu.repo_key }}"

    - name: "(Ubuntu) Add docker apt repository"
      apt_repository:
        repo: "{{ docker.ubuntu.repo_url }}"

    - name: "(Ubuntu) Install docker-ce"
      apt:
        name: "{{ docker.ubuntu.install_list }}"
        update_cache: true
        state: present
      notify: enable and start docker
